### ISSUE TITLE
Release process appears to be broken with no new binaries

### ISSUE THREAD

**Issue by alexellis** [kastenhq/kubestr#235]
The release process appears to be broken with no new binaries for the last two releases

This has caused the e2e tests to fail for arkade.

https://github.com/alexellis/arkade/actions/runs/8397818892/job/23001769640

Please could the maintainers either mark the erroneous releases as "pre-release" therefore removing them as the "latest" release, or make new binaries and attach them to the latest release.

cc @MichaelCade 

See also: https://github.com/kastenhq/kubestr/releases/tag/v0.4.42

"2 files" - no binaries. This normally has ~ 9 files when the release process is working.

**Comment by shuguet** [comment]
Hello @alexellis !

Thank you for reporting the issue.

It appears there has been some changes in the list of authorized GitHub Actions at the org level, we're tracking down the issue as I write this.

I'll let @bathina2 @julio-lopez @pavannd1 and @hairyhum make the call on reverting the release status to pre-release in order to unblock you 🙏

**Comment by shuguet** [comment]
Hello @alexellis ,

Sorry for the delay, and thank you for raising this to our attention 🙏

We just pushed a new release that has all the bits attached/went through all the proper steps.

We've also moved the previous release to pre-release status, so hopefully it shouldn't impact Arkade anymore.

I'll close this issue now, feel free to re-open it if there's anything more needed.

Again, thank you for reaching out!

**Comment by alexellis** [comment]
No worries. Closed downstream in arkade now that this is fixed.
